### ISSUE TITLE
Thank you for the RSS example

### ISSUE THREAD

**Issue by deadcoder0904** [IanMitchell/ianmitchell.dev#3]
I used your [RSS example to generate the feed](https://github.com/tailwindlabs/blog.tailwindcss.com/pull/20) so thank you for that.

Also, I read https://ianmitchell.dev/blog/building-a-nextjs-blog-static-mdx & the big caveat you mention can be solved by using a loader in `next.config.js` as [Tailwind Blog](https://github.com/tailwindlabs/blog.tailwindcss.com/) does it. This way it supports client-side hydration :)

**Comment by IanMitchell** [comment]
Hey! I am so sorry I missed this - I didn't receive a notification for some reason, and I just never check the repo. Really glad that you found it useful!

I just switched over to a new system that supports hydration actually 👀. Super excited for it! I should probably update the blog post with some new info haha. Also gotta figure out why Webpack 5 breaks it.

Glad you found it useful though, thank you for letting me know! And again, so so sorry I didn't respond until just now

**Comment by deadcoder0904** [comment]
No problem, Github & Twitter notifications don't work that great for me either. Happened to me quite a few times as well.

I just saw your blog. It looks different I think. Congrats on joining Discord bdw. I am using it a lot nowadays to get into niche communities.

**Comment by IanMitchell** [comment]
Thanks! I’m super excited for it! Yeah, I just published a design update which is why I saw this issue - was in here merging some stuff haha
